apiVersion: v1
kind: Service
metadata:
  labels:
    service: m-coworkingspace-service
  name: m-coworkingspace-service
spec:
  type: ClusterIP
  ports:
  - protocol: "TCP"
    port: 5153
    targetPort: 5153
  selector:
    service: m-coworkingspace-service
